export const CONTRACT_SCHEMA_VERSION = 1 as const;
export const PUBLICATION_SOURCE_SYSTEM = "rp_os" as const;
export const PUBLICATION_PRODUCER_CAPABILITY = "quartel_curriculum_publication" as const;
export const ARTIFACT_TYPES = ["module", "lesson", "quiz", "review", "asset"] as const;
export type ArtifactType = (typeof ARTIFACT_TYPES)[number];
export interface SourceVersion { major: number; minor: number }
export type PublicationRelation = "REPLAY" | "CONFLICT" | "STALE" | "NEWER" | "DIFFERENT_SOURCE";
export type ContentPublicationEnvelopeV1 = Record<string, unknown>;
export type ContentReleaseManifestV1 = Record<string, unknown>;

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const HASH = /^sha256:[0-9a-f]{64}$/;
const RFC3339_TZ = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/;

function err(path: string, message: string): never { throw new TypeError(path + ": " + message); }
function obj(v: unknown, p: string): Record<string, unknown> {
  if (v === null || typeof v !== "object" || Array.isArray(v) || ![Object.prototype, null].includes(Object.getPrototypeOf(v))) err(p, "expected plain object");
  return v as Record<string, unknown>;
}
function exact(o: Record<string, unknown>, allowed: string[], required: string[], p: string): void {
  const a = new Set(allowed);
  for (const k of Object.keys(o)) if (!a.has(k)) err(p + "." + k, "unexpected field");
  for (const k of required) if (!(k in o)) err(p + "." + k, "required field missing");
}
function str(v: unknown, p: string): string { if (typeof v !== "string" || !v.length) err(p, "expected non-empty string"); return v; }
function uuid(v: unknown, p: string): string { const s = str(v,p); if (!UUID.test(s)) err(p,"expected UUID"); return s; }
function hash(v: unknown, p: string): string { const s = str(v,p); if (!HASH.test(s)) err(p,"expected sha256 hash"); return s; }
function integer(v: unknown, p: string, min?: number): number { if (typeof v !== "number" || !Number.isInteger(v) || (min !== undefined && v < min)) err(p,"invalid integer"); return v; }
function bool(v: unknown, p: string): boolean { if (typeof v !== "boolean") err(p,"expected boolean"); return v; }
function dt(v: unknown, p: string): string { const s=str(v,p); if(!RFC3339_TZ.test(s)||Number.isNaN(Date.parse(s))) err(p,"expected RFC3339 date-time with explicit timezone"); return s; }
function arr(v: unknown, p: string, min=0): unknown[] { if(!Array.isArray(v)||v.length<min) err(p,"invalid array"); return v; }
function one<T extends readonly string[]>(v: unknown, values: T, p: string): T[number] { const s=str(v,p); if(!(values as readonly string[]).includes(s)) err(p,"unsupported value"); return s as T[number]; }
function version(v: unknown, p: string): SourceVersion { const o=obj(v,p); exact(o,["major","minor"],["major","minor"],p); return {major:integer(o.major,p+".major",0),minor:integer(o.minor,p+".minor",0)}; }

function json(v: unknown, p: string): unknown {
  if (v === null || typeof v === "string" || typeof v === "boolean") return v;
  if (typeof v === "number") { if (!Number.isFinite(v)) err(p,"non-finite number"); return Object.is(v,-0)?0:v; }
  if (Array.isArray(v)) return v.map((x,i)=>json(x,p+"["+i+"]"));
  const o=obj(v,p), out: Record<string,unknown>={}; for(const k of Object.keys(o)) out[k]=json(o[k],p+"."+k); return out;
}
function canon(v: unknown): unknown { const n=json(v,"$root"); if(n===null||typeof n!=="object") return n; if(Array.isArray(n)) return n.map(canon); const out:Record<string,unknown>={}; for(const k of Object.keys(n as Record<string,unknown>).sort()) out[k]=canon((n as Record<string,unknown>)[k]); return out; }
export function canonicalStringify(v: unknown): string { return JSON.stringify(canon(v)); }
export async function computeContentHash(v: unknown): Promise<string> { const bytes=new TextEncoder().encode(canonicalStringify(v)); const digest=await crypto.subtle.digest("SHA-256",bytes); const hex=Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join(""); return ("sha256:"+hex); }
export async function verifyContentHash(v: unknown, expected: string): Promise<boolean> { return HASH.test(expected) && await computeContentHash(v)===expected; }

export function compareSourceVersion(a: SourceVersion,b: SourceVersion):-1|0|1 { if(a.major!==b.major) return a.major<b.major?-1:1; if(a.minor!==b.minor) return a.minor<b.minor?-1:1; return 0; }
export function formatSourceVersion(v: SourceVersion): string { return String(v.major)+"."+String(v.minor); }
export async function buildIdempotencyKey(i:{source_system?:typeof PUBLICATION_SOURCE_SYSTEM;artifact_type:ArtifactType;stable_source_id:string;source_version:SourceVersion}):Promise<string>{ return "qcp:v1:"+await computeContentHash({source_system:i.source_system??PUBLICATION_SOURCE_SYSTEM,artifact_type:i.artifact_type,stable_source_id:i.stable_source_id,source_version:formatSourceVersion(i.source_version)}); }
export function classifyIncomingPublication(e:{stable_source_id:string;source_version:SourceVersion;content_hash:string},i:{stable_source_id:string;source_version:SourceVersion;content_hash:string}):PublicationRelation { if(e.stable_source_id!==i.stable_source_id)return"DIFFERENT_SOURCE"; const c=compareSourceVersion(i.source_version,e.source_version); if(c<0)return"STALE"; if(c>0)return"NEWER"; return e.content_hash===i.content_hash?"REPLAY":"CONFLICT"; }

function artifactRef(v: unknown,p:string):void{ const o=obj(v,p); exact(o,["stable_source_id","artifact_version_id","content_hash"],["stable_source_id","artifact_version_id"],p); uuid(o.stable_source_id,p+".stable_source_id"); uuid(o.artifact_version_id,p+".artifact_version_id"); if(o.content_hash!==undefined)hash(o.content_hash,p+".content_hash"); }
function payload(type:ArtifactType,v:unknown,p:string):void{
  const o=obj(v,p);
  if(type==="module"){ exact(o,["title","description","force","sequence_order","active"],["title","force","sequence_order","active"],p); str(o.title,p+".title"); if(o.description!==undefined)str(o.description,p+".description"); one(o.force,["marinha","exercito","aeronautica"] as const,p+".force"); integer(o.sequence_order,p+".sequence_order"); bool(o.active,p+".active"); return; }
  if(type==="lesson"){ exact(o,["module_source_id","title","description","sequence_order","learning_objectives","estimated_duration_minutes","content","media_refs"],["module_source_id","title","sequence_order","learning_objectives","content","media_refs"],p); uuid(o.module_source_id,p+".module_source_id"); str(o.title,p+".title"); if(o.description!==undefined)str(o.description,p+".description"); integer(o.sequence_order,p+".sequence_order"); arr(o.learning_objectives,p+".learning_objectives").forEach((x,i)=>str(x,p+".learning_objectives["+i+"]")); if(o.estimated_duration_minutes!==undefined)integer(o.estimated_duration_minutes,p+".estimated_duration_minutes",1); json(o.content,p+".content"); arr(o.media_refs,p+".media_refs").forEach((x,i)=>artifactRef(x,p+".media_refs["+i+"]")); return; }
  if(type==="review"){ exact(o,["lesson_source_id","review_type","content","media_refs"],["lesson_source_id","review_type","content","media_refs"],p); uuid(o.lesson_source_id,p+".lesson_source_id"); str(o.review_type,p+".review_type"); json(o.content,p+".content"); arr(o.media_refs,p+".media_refs").forEach((x,i)=>artifactRef(x,p+".media_refs["+i+"]")); return; }
  if(type==="asset"){ exact(o,["media_type","checksum","immutable_reference","metadata"],["media_type","checksum","immutable_reference","metadata"],p); str(o.media_type,p+".media_type"); hash(o.checksum,p+".checksum"); str(o.immutable_reference,p+".immutable_reference"); if(o.metadata!==null)json(o.metadata,p+".metadata"); return; }
  exact(o,["scope","lesson_source_id","module_source_id","title","questions"],["scope","lesson_source_id","module_source_id","title","questions"],p); const scope=one(o.scope,["lesson","module"] as const,p+".scope"); if(scope==="lesson"){uuid(o.lesson_source_id,p+".lesson_source_id");if(o.module_source_id!==null)err(p+".module_source_id","must be null for lesson scope");}else{uuid(o.module_source_id,p+".module_source_id");if(o.lesson_source_id!==null)err(p+".lesson_source_id","must be null for module scope");} str(o.title,p+".title"); const qids=new Set<string>(); arr(o.questions,p+".questions",1).forEach((qv,qi)=>{const q=obj(qv,p+".questions["+qi+"]");exact(q,["stable_question_id","version_id","order","text","explanation","alternatives"],["stable_question_id","version_id","order","text","alternatives"],p+".questions["+qi+"]");const qid=uuid(q.stable_question_id,p+".questions["+qi+"].stable_question_id");if(qids.has(qid))err(p+".questions","duplicate stable_question_id");qids.add(qid);uuid(q.version_id,p+".questions["+qi+"].version_id");integer(q.order,p+".questions["+qi+"].order");str(q.text,p+".questions["+qi+"].text");if(q.explanation!==undefined)str(q.explanation,p+".questions["+qi+"].explanation");const aids=new Set<string>();let correct=0;arr(q.alternatives,p+".questions["+qi+"].alternatives",1).forEach((av,ai)=>{const a=obj(av,p+".questions["+qi+"].alternatives["+ai+"]");exact(a,["stable_alternative_id","text","correct"],["stable_alternative_id","text","correct"],p);const aid=uuid(a.stable_alternative_id,p+".questions["+qi+"].alternatives["+ai+"].stable_alternative_id");if(aids.has(aid))err(p,"duplicate stable_alternative_id");aids.add(aid);str(a.text,p+".questions["+qi+"].alternatives["+ai+"].text");if(bool(a.correct,p+".questions["+qi+"].alternatives["+ai+"].correct"))correct++;});if(correct!==1)err(p+".questions["+qi+"]","must have exactly one correct alternative");});
}

export async function parsePublicationEnvelopeV1(input:unknown):Promise<ContentPublicationEnvelopeV1>{
  const e=obj(input,"$envelope"); exact(e,["contract_schema_version","publication_id","producer","artifact","approval","provenance","release","timing","supersession","idempotency","payload"],["contract_schema_version","publication_id","producer","artifact","approval","provenance","release","timing","supersession","idempotency","payload"],"$envelope"); if(e.contract_schema_version!==1)err("$envelope.contract_schema_version","unsupported version"); uuid(e.publication_id,"$envelope.publication_id");
  const producer=obj(e.producer,"$envelope.producer");exact(producer,["system","capability"],["system","capability"],"$envelope.producer");if(producer.system!==PUBLICATION_SOURCE_SYSTEM||producer.capability!==PUBLICATION_PRODUCER_CAPABILITY)err("$envelope.producer","unexpected producer");
  const a=obj(e.artifact,"$envelope.artifact");exact(a,["type","stable_source_id","stable_code","source_version","artifact_version_id","content_hash","state"],["type","stable_source_id","source_version","artifact_version_id","content_hash","state"],"$envelope.artifact");const type=one(a.type,ARTIFACT_TYPES,"$envelope.artifact.type");const sid=uuid(a.stable_source_id,"$envelope.artifact.stable_source_id");if(a.stable_code!==undefined)str(a.stable_code,"$envelope.artifact.stable_code");const sv=version(a.source_version,"$envelope.artifact.source_version");uuid(a.artifact_version_id,"$envelope.artifact.artifact_version_id");const ch=hash(a.content_hash,"$envelope.artifact.content_hash");if(a.state!=="published")err("$envelope.artifact.state","must be published");
  const ap=obj(e.approval,"$envelope.approval");exact(ap,["state","approved_at","approved_by_ref"],["state","approved_at","approved_by_ref"],"$envelope.approval");if(ap.state!=="approved")err("$envelope.approval.state","must be approved");dt(ap.approved_at,"$envelope.approval.approved_at");str(ap.approved_by_ref,"$envelope.approval.approved_by_ref");
  const pr=obj(e.provenance,"$envelope.provenance");exact(pr,["source_reference","authority_body","curriculum_version","master_artifact_ref","derived_from","generator"],["source_reference","authority_body","curriculum_version"],"$envelope.provenance");str(pr.source_reference,"$envelope.provenance.source_reference");str(pr.authority_body,"$envelope.provenance.authority_body");str(pr.curriculum_version,"$envelope.provenance.curriculum_version");if(pr.master_artifact_ref!==undefined){const r=obj(pr.master_artifact_ref,"$envelope.provenance.master_artifact_ref");exact(r,["stable_id","version_id"],["stable_id","version_id"],"$envelope.provenance.master_artifact_ref");uuid(r.stable_id,"stable_id");uuid(r.version_id,"version_id");}if(pr.derived_from!==undefined)arr(pr.derived_from,"$envelope.provenance.derived_from").forEach((rv,i)=>{const r=obj(rv,"derived_from");exact(r,["stable_id","version_id"],["stable_id","version_id"],"derived_from");uuid(r.stable_id,"derived_from["+i+"].stable_id");uuid(r.version_id,"derived_from["+i+"].version_id");});if(pr.generator!==undefined){const g=obj(pr.generator,"$envelope.provenance.generator");exact(g,["name","version"],[],"$envelope.provenance.generator");if(g.name!==undefined)str(g.name,"generator.name");if(g.version!==undefined)str(g.version,"generator.version");}
  const r=obj(e.release,"$envelope.release");exact(r,["release_id","release_code","release_sequence"],["release_id","release_code","release_sequence"],"$envelope.release");uuid(r.release_id,"release_id");str(r.release_code,"release_code");integer(r.release_sequence,"release_sequence",1);
  const t=obj(e.timing,"$envelope.timing");exact(t,["published_at","effective_at"],["published_at","effective_at"],"$envelope.timing");dt(t.published_at,"published_at");if(t.effective_at!==null)dt(t.effective_at,"effective_at");const s=obj(e.supersession,"$envelope.supersession");exact(s,["supersedes_artifact_version_id"],["supersedes_artifact_version_id"],"$envelope.supersession");if(s.supersedes_artifact_version_id!==null)uuid(s.supersedes_artifact_version_id,"supersedes_artifact_version_id");
  const id=obj(e.idempotency,"$envelope.idempotency");exact(id,["key"],["key"],"$envelope.idempotency");const p=obj(e.payload,"$envelope.payload");exact(p,[type],[type],"$envelope.payload");payload(type,p[type],"$envelope.payload."+type);if(!await verifyContentHash(p[type],ch))err("$envelope.artifact.content_hash","hash mismatch");const expected=await buildIdempotencyKey({artifact_type:type,stable_source_id:sid,source_version:sv});if(id.key!==expected)err("$envelope.idempotency.key","idempotency mismatch");return e;
}
export function getPublicationArtifactPayload(e:ContentPublicationEnvelopeV1):unknown{const a=obj(e.artifact,"artifact");const p=obj(e.payload,"payload");return p[str(a.type,"artifact.type")];}

function releaseRef(v:unknown,p:string):Record<string,unknown>{const o=obj(v,p);exact(o,["artifact_type","stable_source_id","source_version","artifact_version_id","content_hash"],["artifact_type","stable_source_id","source_version","artifact_version_id","content_hash"],p);one(o.artifact_type,ARTIFACT_TYPES,p+".artifact_type");uuid(o.stable_source_id,p+".stable_source_id");version(o.source_version,p+".source_version");uuid(o.artifact_version_id,p+".artifact_version_id");hash(o.content_hash,p+".content_hash");return o;}
function sortedRefs(xs:Record<string,unknown>[]):Record<string,unknown>[] { return [...xs].sort((a,b)=>{const av=version(a.source_version,"v"),bv=version(b.source_version,"v");const l=[a.artifact_type,a.stable_source_id,formatSourceVersion(av),a.artifact_version_id].join("|");const r=[b.artifact_type,b.stable_source_id,formatSourceVersion(bv),b.artifact_version_id].join("|");return l<r?-1:l>r?1:0;}); }
export function releaseManifestHashInput(m:ContentReleaseManifestV1):ContentReleaseManifestV1{const o={...m};delete o.manifest_hash;o.artifacts=sortedRefs(arr(o.artifacts,"artifacts",1).map((x,i)=>releaseRef(x,"artifacts["+i+"]")));return o;}
export async function computeReleaseManifestHash(m:ContentReleaseManifestV1):Promise<string>{return computeContentHash(releaseManifestHashInput(m));}
export async function parseContentReleaseManifestV1(input:unknown):Promise<ContentReleaseManifestV1>{const m=obj(input,"$manifest");exact(m,["contract_schema_version","release_id","release_code","release_sequence","producer","artifacts","published_at","manifest_hash"],["contract_schema_version","release_id","release_code","release_sequence","producer","artifacts","published_at","manifest_hash"],"$manifest");if(m.contract_schema_version!==1)err("contract_schema_version","unsupported version");uuid(m.release_id,"release_id");str(m.release_code,"release_code");integer(m.release_sequence,"release_sequence",1);const p=obj(m.producer,"producer");exact(p,["system"],["system"],"producer");if(p.system!==PUBLICATION_SOURCE_SYSTEM)err("producer.system","unexpected producer");dt(m.published_at,"published_at");hash(m.manifest_hash,"manifest_hash");const exactSet=new Set<string>(),logicalSet=new Set<string>();arr(m.artifacts,"artifacts",1).forEach((x,i)=>{const r=releaseRef(x,"artifacts["+i+"]");const v=version(r.source_version,"version");const ex=[r.artifact_type,r.stable_source_id,formatSourceVersion(v),r.artifact_version_id,r.content_hash].join("|");const lo=[r.artifact_type,r.stable_source_id,formatSourceVersion(v)].join("|");if(exactSet.has(ex))err("artifacts","duplicate artifact reference");if(logicalSet.has(lo))err("artifacts","duplicate logical source/version");exactSet.add(ex);logicalSet.add(lo);});if(m.manifest_hash!==await computeReleaseManifestHash(m))err("manifest_hash","manifest hash mismatch");return m;}
