import assert from "node:assert/strict";
import { buildIdempotencyKey, canonicalStringify, classifyIncomingPublication, computeContentHash, computeReleaseManifestHash, parseContentReleaseManifestV1, parsePublicationEnvelopeV1 } from "./contract.ts";

const ids={module:"11111111-1111-4111-8111-111111111111",lesson:"33333333-3333-4333-8333-333333333333",quiz:"77777777-7777-4777-8777-777777777777",review:"88888888-8888-4888-8888-888888888888",asset:"99999999-9999-4999-8999-999999999999",artifact:"22222222-2222-4222-8222-222222222222",release:"55555555-5555-4555-8555-555555555555",q:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",a:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",b:"cccccccc-cccc-4ccc-8ccc-cccccccccccc"};
function payload(type:string):any{if(type==="module")return{title:"Módulo",force:"marinha",sequence_order:1,active:true};if(type==="lesson")return{module_source_id:ids.module,title:"Aula",sequence_order:1,learning_objectives:["Aprender"],content:{b:2,a:1},media_refs:[]};if(type==="quiz")return{scope:"lesson",lesson_source_id:ids.lesson,module_source_id:null,title:"Quiz",questions:[{stable_question_id:ids.q,version_id:ids.artifact,order:1,text:"Q?",alternatives:[{stable_alternative_id:ids.a,text:"A",correct:true},{stable_alternative_id:ids.b,text:"B",correct:false}]}]};if(type==="review")return{lesson_source_id:ids.lesson,review_type:"summary",content:{text:"R"},media_refs:[]};return{media_type:"audio",checksum:"sha256:"+"a".repeat(64),immutable_reference:"s3://immutable",metadata:null};}
async function publication(type:any){const stable:any={module:ids.module,lesson:ids.lesson,quiz:ids.quiz,review:ids.review,asset:ids.asset};const p=payload(type),sv={major:1,minor:0},sid=stable[type];return{contract_schema_version:1,publication_id:"dddddddd-dddd-4ddd-8ddd-dddddddddddd",producer:{system:"rp_os",capability:"quartel_curriculum_publication"},artifact:{type,stable_source_id:sid,stable_code:"QD."+type,source_version:sv,artifact_version_id:ids.artifact,content_hash:await computeContentHash(p),state:"published"},approval:{state:"approved",approved_at:"2026-09-20T10:00:00Z",approved_by_ref:"board"},provenance:{source_reference:"manual",authority_body:"RP OS",curriculum_version:"2026.09"},release:{release_id:ids.release,release_code:"QD-1",release_sequence:1},timing:{published_at:"2026-09-20T11:00:00Z",effective_at:null},supersession:{supersedes_artifact_version_id:null},idempotency:{key:await buildIdempotencyKey({artifact_type:type,stable_source_id:sid,source_version:sv})},payload:{[type]:p}};}
let failed=0;async function check(name:string,fn:()=>unknown|Promise<unknown>){try{await fn();console.log("  ✔ "+name);}catch(e){failed++;console.error("  ✗ "+name+"\n    "+(e as Error).message);}}
console.log("Gate 5A — consumer contract conformance tests");
await check("canonical JSON orders keys",()=>assert.equal(canonicalStringify({b:2,a:1}),'{"a":1,"b":2}'));
await check("semantic payload hash is stable",async()=>assert.equal(await computeContentHash({a:1,b:2}),await computeContentHash({b:2,a:1})));
await check("non-finite JSON fails closed",()=>assert.throws(()=>canonicalStringify({x:NaN})));
for(const type of ["module","lesson","quiz","review","asset"] as const)await check("parses "+type,async()=>assert.equal(((await parsePublicationEnvelopeV1(await publication(type))).artifact as any).type,type));
await check("rejects hash mismatch",async()=>{const x:any=await publication("module");x.artifact.content_hash="sha256:"+"b".repeat(64);await assert.rejects(()=>parsePublicationEnvelopeV1(x));});
await check("rejects unknown contract schema",async()=>{const x:any=await publication("module");x.contract_schema_version=2;await assert.rejects(()=>parsePublicationEnvelopeV1(x));});
await check("rejects learner-state leakage",async()=>{const x:any=await publication("module");x.payload.module.recruta_id="leak";x.artifact.content_hash=await computeContentHash(x.payload.module);await assert.rejects(()=>parsePublicationEnvelopeV1(x));});
await check("rejects wrong idempotency",async()=>{const x:any=await publication("module");x.idempotency.key="wrong";await assert.rejects(()=>parsePublicationEnvelopeV1(x));});
await check("rejects quiz with two correct answers",async()=>{const x:any=await publication("quiz");x.payload.quiz.questions[0].alternatives[1].correct=true;x.artifact.content_hash=await computeContentHash(x.payload.quiz);await assert.rejects(()=>parsePublicationEnvelopeV1(x));});
await check("accepts explicit timezone offset",async()=>{const x:any=await publication("module");x.approval.approved_at="2026-09-20T10:00:00-03:00";await parsePublicationEnvelopeV1(x);});
await check("rejects timezone-less date",async()=>{const x:any=await publication("module");x.approval.approved_at="2026-09-20T10:00:00";await assert.rejects(()=>parsePublicationEnvelopeV1(x));});
await check("classifies version relation",()=>{const e={stable_source_id:ids.module,source_version:{major:2,minor:0},content_hash:"sha256:"+"a".repeat(64)};assert.equal(classifyIncomingPublication(e,{...e}),"REPLAY");assert.equal(classifyIncomingPublication(e,{...e,content_hash:"sha256:"+"b".repeat(64)}),"CONFLICT");assert.equal(classifyIncomingPublication(e,{...e,source_version:{major:1,minor:9}}),"STALE");assert.equal(classifyIncomingPublication(e,{...e,source_version:{major:2,minor:1}}),"NEWER");});
const artifacts=[{artifact_type:"module",stable_source_id:"11111111-1111-4111-8111-111111111111",source_version:{major:1,minor:0},artifact_version_id:"22222222-2222-4222-8222-222222222222",content_hash:"sha256:"+"a".repeat(64)},{artifact_type:"lesson",stable_source_id:"33333333-3333-4333-8333-333333333333",source_version:{major:1,minor:0},artifact_version_id:"44444444-4444-4444-8444-444444444444",content_hash:"sha256:"+"b".repeat(64)}];
const base:any={contract_schema_version:1,release_id:"55555555-5555-4555-8555-555555555555",release_code:"QD-MAR-2026.001",release_sequence:1,producer:{system:"rp_os"},artifacts,published_at:"2026-09-20T10:00:00.000Z"};
await check("matches producer golden release hash",async()=>assert.equal(await computeReleaseManifestHash(base),"sha256:89c98ec6d7ad5714eac317ef0fc9f9c8e5db57c444578d3abce3448bf836a03e"));
await check("release hash is order-independent",async()=>assert.equal(await computeReleaseManifestHash(base),await computeReleaseManifestHash({...base,artifacts:[...artifacts].reverse()})));
await check("parses release and rejects duplicate logical source",async()=>{const m:any={...base,manifest_hash:await computeReleaseManifestHash(base)};await parseContentReleaseManifestV1(m);const dup=[artifacts[0],{...artifacts[0],artifact_version_id:"66666666-6666-4666-8666-666666666666",content_hash:"sha256:"+"c".repeat(64)}];const bad:any={...base,artifacts:dup};bad.manifest_hash=await computeReleaseManifestHash(bad);await assert.rejects(()=>parseContentReleaseManifestV1(bad));});
if(failed){console.error("\n❌ "+failed+" test(s) failed");process.exit(1);}console.log("\n✅ consumer conformance mirror PASS");
